### ISSUE TITLE
Support saving labeled grids, like standard Prompt Matrix

### ISSUE THREAD

**Issue by appleguy** [ArrowM/auto1111-improved-prompt-matrix#1]
Thanks for this improvement! The ability to run batches across multiple seeds is a very significant win for the capabilities of the SD community.

That said, for some use cases, the grid format with text labels can be very valuable. Would it be simple to support this feature of the original script? Even if hardcoded rather than exposed as a UI option, this would be great to have.

**Comment by axemaster** [comment]
This script is a big improvement as the original is useless to me. I would also like to have labeled grids and support for batch count >1. Thanks for considering!
