### ISSUE TITLE
Please let us choose "random seed for every image"

### ISSUE THREAD

**Issue by vkleinmp** [ArrowM/auto1111-improved-prompt-matrix#2]

**Comment by jamesdesmond** [comment]
I found this issue, looking for the same feature.

My first thought was to use the code here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5438/commits/fa6478796a5c794b4141fce3e8cdb9ec5ea2b71f where randomized seeds were included in the original (non-improved) prompt matrix.

But that code seems to just add 1 to the seed each time,

If we look at the code for the improved prompt matrix: https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py#L60 this is also happening, I am going to mess around locally and see if I can get it to work

**Comment by ArrowM** [comment]
This was a quick low-effort script. For a more flushed out version, add this extension: https://github.com/adieyal/sd-dynamic-prompts
