### ISSUE TITLE
Script doesn't correctly handle usage of | character for other purposes

### ISSUE THREAD

**Issue by nothings** [ArrowM/auto1111-improved-prompt-matrix#3]
When running the Improved prompt matrix script,
```<cow|horse>```
works and produces two images, a cow and a horse.

Meanwhile, this other syntax supported by webui is unaffected:
```[cow|horse]```
and produces a single image of a cow-horse.

Where it breaks is when they're combined:
```<[cow|horse] | dog>```
This ought to produce two pictures, one of a cow-horse, and one of a dog. Instead it produces three pictures, one of each type. Apparently Improved prompt matrix is treating all "|" inside the <> as belonging to it, but that's not right; you need to ignore | that are inside [ ] pairs.

Also, this:
```< [[cow|horse]:goat:5] | dog >```
crashes the SD parser with an Index out of range after Improved prompt matrix updates the prompt, presumably because the extra unmatched ```]```s and ```:```s output by the script (copied from the misparsed prompt) are just too much for it.

**Comment by igor-kurenkov** [comment]
Ignores the angle brackets <> completely, For each variant removes everything on the other side of '|'
