### ISSUE TITLE
Conflicts with Extra networks feature

### ISSUE THREAD

**Issue by younyokel** [ArrowM/auto1111-improved-prompt-matrix#4]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#extra-networks

Extra networks load hypernets and LORAs in the same way as this script does, and so WebUI gives an error when I use both this script and the extra networks.

**Comment by speshiou** [comment]
I've made some improvements about that.
https://github.com/speshiou/auto1111-improved-prompt-matrix
