### ISSUE TITLE
Isn't the <some_word_here_syntax> already used for including Loras?

### ISSUE THREAD

**Issue by illtellyoulater** [ArrowM/auto1111-improved-prompt-matrix#6]
Now that Loras got so widespread wouldn't it be a good idea to switch to a different syntax?

Also, are there still any advantages in using this script now that [XYZ-grid](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/scripts/xyz_grid.py) is included in Web-UI ?

**Comment by ArrowM** [comment]
This extension was a quick throw away project. I would recommend using the integrated XYZ-grid or Dynamic Prompts extensions now instead of this script. I'll add that info to the readme of this repo.
